"""
SQLite database schema initialization.

This module defines the relational database structure used by the
Banking Services AI Assistant.

The schema separates customer identity, credit accounts, mortgage
contracts, mortgage observations, model metadata, and prediction
history.
"""

from database.connection import get_connection


SCHEMA_SQL = """
-- 1. CLIENTS
-- Master customer information.


CREATE TABLE IF NOT EXISTS clients (
    client_id INTEGER PRIMARY KEY AUTOINCREMENT,

    -- Business-facing customer identifier.
    customer_number TEXT NOT NULL UNIQUE,

    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    date_of_birth TEXT,

    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- 2. CREDIT ACCOUNTS
-- Credit-card / revolving-credit information used by the
-- application credit-risk model.

CREATE TABLE IF NOT EXISTS credit_accounts (
    credit_account_id INTEGER PRIMARY KEY AUTOINCREMENT,

    -- Business-facing account identifier.
    account_number TEXT NOT NULL UNIQUE,

    client_id INTEGER NOT NULL,

    credit_limit REAL NOT NULL,

    -- Demographic variables currently required by the
    -- trained UCI credit-risk model.
    sex INTEGER,
    education INTEGER,
    marital_status INTEGER,
    age INTEGER,

    -- Six months of repayment status.
    payment_status_1 INTEGER,
    payment_status_2 INTEGER,
    payment_status_3 INTEGER,
    payment_status_4 INTEGER,
    payment_status_5 INTEGER,
    payment_status_6 INTEGER,

    -- Six months of statement balances.
    bill_amount_1 REAL,
    bill_amount_2 REAL,
    bill_amount_3 REAL,
    bill_amount_4 REAL,
    bill_amount_5 REAL,
    bill_amount_6 REAL,

    -- Six months of payments.
    payment_amount_1 REAL,
    payment_amount_2 REAL,
    payment_amount_3 REAL,
    payment_amount_4 REAL,
    payment_amount_5 REAL,
    payment_amount_6 REAL,

    account_status TEXT NOT NULL DEFAULT 'ACTIVE',

    opened_at TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (client_id)
        REFERENCES clients(client_id)
        ON DELETE RESTRICT
);


-- 3. MORTGAGES
-- Mortgage contract / origination information.
-- These characteristics generally describe the loan itself
-- rather than a particular monthly observation.

CREATE TABLE IF NOT EXISTS mortgages (
    mortgage_id INTEGER PRIMARY KEY AUTOINCREMENT,

    -- Business-facing mortgage identifier.
    loan_number TEXT NOT NULL UNIQUE,

    client_id INTEGER NOT NULL,

    credit_score INTEGER,
    original_dti REAL,
    original_upb REAL,
    original_ltv REAL,
    original_interest_rate REAL,

    first_time_homebuyer_flag TEXT,
    occupancy_status TEXT,
    channel TEXT,
    property_type TEXT,
    loan_purpose TEXT,

    origination_date TEXT,
    maturity_date TEXT,

    loan_status TEXT NOT NULL DEFAULT 'ACTIVE',

    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (client_id)
        REFERENCES clients(client_id)
        ON DELETE RESTRICT
);


-- 4. MORTGAGE OBSERVATIONS
-- Time-varying mortgage performance information.
-- A mortgage may have many observations over its lifetime.

CREATE TABLE IF NOT EXISTS mortgage_observations (
    observation_id INTEGER PRIMARY KEY AUTOINCREMENT,

    mortgage_id INTEGER NOT NULL,

    observation_date TEXT NOT NULL,
    loan_age INTEGER,

    current_actual_upb REAL,
    current_interest_rate REAL,
    current_loan_delinquency_status INTEGER,

    estimated_ltv REAL,
    balance_paydown_ratio REAL,

    remaining_months_to_maturity INTEGER,

    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (mortgage_id)
        REFERENCES mortgages(mortgage_id)
        ON DELETE CASCADE,

    UNIQUE(mortgage_id, observation_date)
);


-- 5. MODEL REGISTRY
-- Metadata describing ML models available to the application.

CREATE TABLE IF NOT EXISTS model_registry (
    model_registry_id INTEGER PRIMARY KEY AUTOINCREMENT,

    -- Stable application identifier such as mortgage_pd.
    model_key TEXT NOT NULL,

    model_name TEXT NOT NULL,
    model_version TEXT NOT NULL,
    model_type TEXT NOT NULL,

    artifact_filename TEXT NOT NULL,

    target_name TEXT,
    model_status TEXT NOT NULL DEFAULT 'ACTIVE',

    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,

    UNIQUE(model_key, model_version)
);


-- 6. RISK PREDICTIONS
-- Historical predictions generated by registered ML models.

CREATE TABLE IF NOT EXISTS risk_predictions (
    prediction_id INTEGER PRIMARY KEY AUTOINCREMENT,

    client_id INTEGER NOT NULL,

    -- Depending on the model, the prediction may relate to a
    -- credit account, mortgage, or mortgage observation.
    credit_account_id INTEGER,
    mortgage_id INTEGER,
    observation_id INTEGER,

    model_registry_id INTEGER NOT NULL,

    prediction_type TEXT NOT NULL,
    prediction_value REAL NOT NULL,

    threshold REAL,
    prediction_label TEXT,

    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (client_id)
        REFERENCES clients(client_id)
        ON DELETE RESTRICT,

    FOREIGN KEY (credit_account_id)
        REFERENCES credit_accounts(credit_account_id)
        ON DELETE SET NULL,

    FOREIGN KEY (mortgage_id)
        REFERENCES mortgages(mortgage_id)
        ON DELETE SET NULL,

    FOREIGN KEY (observation_id)
        REFERENCES mortgage_observations(observation_id)
        ON DELETE SET NULL,

    FOREIGN KEY (model_registry_id)
        REFERENCES model_registry(model_registry_id)
        ON DELETE RESTRICT
);


-- INDEXES
-- Improve lookup performance for common application queries.

CREATE INDEX IF NOT EXISTS idx_clients_name
ON clients(last_name, first_name);

CREATE INDEX IF NOT EXISTS idx_credit_accounts_client
ON credit_accounts(client_id);

CREATE INDEX IF NOT EXISTS idx_mortgages_client
ON mortgages(client_id);

CREATE INDEX IF NOT EXISTS idx_mortgage_observations_mortgage
ON mortgage_observations(mortgage_id);

CREATE INDEX IF NOT EXISTS idx_mortgage_observations_date
ON mortgage_observations(observation_date);

CREATE INDEX IF NOT EXISTS idx_predictions_client
ON risk_predictions(client_id);

CREATE INDEX IF NOT EXISTS idx_predictions_model
ON risk_predictions(model_registry_id);
"""


def initialize_database() -> None:
    """
    Create all application database tables and indexes.

    Existing tables are preserved because CREATE TABLE IF NOT EXISTS
    is used.
    """

    connection = get_connection()

    try:
        connection.executescript(SCHEMA_SQL)
        connection.commit()
    finally:
        connection.close()


if __name__ == "__main__":
    initialize_database()
    print("Database schema initialized successfully.")